language: python
python:
  - "3.6"
env:
  global:
    - AWS_DEFAULT_REGION=us-east-1
    - secure: "doC7Nqk47eynQZzqJe2PNqW6muHzdA4gYA466zjhWIyyyVvgPPQxd1dlc+jTf0eiLP7lDz/NZYgurUQDTppJAJ0Ui8ZtgqcjiRYGuKQuUjxz4KNIRK+r7O4idEFInMnr+3G/lqTeOrXYiQJJ4QPZi5oQWhMDmh7xgCAwPxU0SFscgBj2qc5jDz7SQXvEi1BjIj/gRF8HZQYq37rmKqVJrJvwGrBhs5aQ04/Yov44Nvz0+1J4RMkvrRwEYwaabkmW6yHd0nnJ1FsClag/3Aj+NCec9uo1fbEbTGkF91mkoHuhjxgLfEtr9bo2ijn32LuZktrkQNU9mkAjSmf3nnGweLCk58fgcwMpXQxiDGETK1kDoZlfh2wJdNTaXIpDU9sRftUbMnJXLjMBEEIADaYwmpNn54+WNHGH8cH6JQlNhtEOZylP/eypVeIDXJDH77GgUWU0Ku3Olp6DAelXe/rkRCBS+DqLcBN1mYW99YbceTh2z8I2+FYAwNdkhghIFNcby/ghaJo7BH1vrxNyEg64LSvZYt7DnPKvat8BjgqCJrNQOfAS9ndboF0Cf9hpzZLWIxCiv/vRI7oEUGhBrnRddxG4tZvUaPfbVB4Uy/rGtezD/EPJ8eHeshIlph2hBzCatyY/1R4ksnVN3rVrvWquZTS9VjaJC/RkCPXalf3YysE="
    - secure: "sVbl7UP00/YKUiloA6dXCn4kbM8X2+asKCvX2fmCqSinpoutAZFKqgq7ZSYAlZsRGJwc308Ne10oEO+je/FKcWPIlR8yiICRPo9fcAxqsap8N905mQJj4Q6iALWzEo0vRK54hnyrTzg/tY3UDWoHnO4kwF2JBvZ5NKi34y/uKHyz490RWsYG2qY4EtY3GGw//Ue3M3SgnIZ2VkneUbv4iUqtUozezXDwi/aD8/NWTB1NQBB+vTMunHjzJKVQW3ZJlwA16M6PpDrghq676VcMXZCvB2nSJ64X2EeaG1OelV+eXXeLvtbLWSjWF/fbu8EhFbNSwwyCfki+84sKBNvZCtR/h5niVP0dcOIrFEszquLci/y44WbwWGjcTlAzHsiNftnV+nNqpjsKu/vOr7D2diPb7iuxzACsUaxumLvyz9bpUljwujIvHe5fTI26T9L/1gfn5uJHBJkdCpTJlL4EvRfRVIoHX4YLAGC1xR//eSS6FqRb8+O7fUv86hYMVqRZi9n/gadpx0solUEj4asmvUdMBYpY7BArSK6Ldi28UnehXfmJwRpixju98TEcH0ZJvE7/3bSMksnLY4ND9AHh2pRyA6ZM5Ov9zmE1uaxz+JFY8OyWXRfGAU704ALFlT1kuQ5l0gPtqdpJ0X2qe8XVJpISkmAfNLCaq0uEYgAXOf8="
install:
  - pip install -r app/f_test/requirements.txt
script: ./run_tests.sh
deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    branch: master
