language: python
python:
  - "3.6"
env:
  global:
    - AWS_DEFAULT_REGION=us-east-1
    - secure: "Zrf/X2JZtcepDWcj2B+ZvRFOYiiL4Sju5wq6fP91JFg+lpI/C4xhjcYCE91VM0sRYvHvj2V0rfcI1nCSdCJ+5sGLdDEYiNJTygtsm6VsTL6F3mFhGLV/Rj/3gxFfG2ykcgTT6mIEpX+CaJXsTapm7ad0TK6JSLPo2x2YJP0961Eq0z+UzCIRfdSD/nLiNIsC8HIOEeL31Aok72GBh8hxV7j3BTMor95TyoRRJWJxwDfkbl19LlTGk100tDhQ7IPsUB+8SjgZbG+a2DyQRDC7O8U40mmNvq8kr9FKuVF80KlYuGrEOwQBimEjWq/5tB+tWkhVVxlgSZMAjgYjcQ35WERa+OYye8gvahYMcS6QB/lcovqFF/l0eeKzEizR2gbyeLPrRagZGpFbbh7CuB7dEbkAGroG0b0tTcC1Xlh5qT4wSxQ015LqBGb21WxmenQ2wXaNT4Vz1D3+QeyHLpKfBJu0OLJuhHGluzx3NqPkqwqFoj8LewC3LiTeJ9ujD1wDC+vyqul9zmErA9xLwfTlADYCSlFTeb79ACy/NklInvwFUk+25Mn1yo5OlmfmQEUhKgctnkZS8Q5Mlp8nmpzAU2XRYcnJkkf5x4E1HqnhzGYSiUqmD+yjisyWpEu9DbvqvbuFPw4YmNbXmwVX15Cef/zjhxr10/+5VS3r6bKF2K4="
    - secure: "kmGGHZ4brhsZPUweqcRmYATXkJuLvnYMw9bGjjVfRq4Dd9xtHnSItwPlsC1pllgGvm0nwGrtrLUKOKwj/swN9UvT081a9X6VIsaQt8NilEFZuC1ycd/1LczdgV62Qjr3xgUwwWYM5Eijpe4rci9aPabpx+/XbFv6Ym+7tz/S7YRU7/FLxxQCFaLnnNQep7InCkErG8dH65MUMF/xjlPeJER/qPK2K7WZQZkp0259PYo7hKS6Fh+1mfWHiJI7C+7QiKDHfd2J7HXduSy+k9aF1kjgxRv1ZfV9DJ8jluD7WErxXiqdJC/LLEN/uLDCUwnRZn12jaMCEsTP7TdUcl5yVx78guxm2HnM/PWg9hGPa5jDClBN6LSj+vMO9gck/MhA5ScARugdN34rLPHvQQA1MY0GvO6NQvw/aWzQjafjMbBZJh9q36EyHgAQ0geHXmRK7OKjKYZLqTOJjj3zUPSywGq6CbRjPG697LIyBaTM5E8s1wU95aeGv1/bVHyBz5T9eu/9iwyGF8kNhm+LH5fEdgVBD3lY5lwDj32ORzvWJk6G8jKaxQ7GQS9jrEq8Agx6rZE3uLsC1SkuZyeE1yO1KqCTqsOlMYu9MWbbAXyYqBIxQsIz3xgObtL8UdZ2MbYtoFIIT/xOd+YT4G0zI6nlspbDlcoHNj2IPC7gcl8L3A0="
install:
  - pip install -r app/f_test/requirements.txt
script: run_tests.sh
deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    branch: master
