language: python
python:
  - "3.6"
env:
  global:
    - AWS_DEFAULT_REGION=us-east-1
    - secure: "NTnXgj5hCkrjs94poA/7dd50QztRrQD51CYi/jsuVcmMJIorX/Fx355u6Ft3zSvtYlx6ZQaxWu3EF8DnjusYoD/nz9+WeVH8Nv78CyWYpn8uETRzAsqIpad0yELxZGcpHocDOPUVYG8b+rgtSufzkriI90cLlR08EjVxrMAIXaXqHa6ewh380IeqB6j2VRZTpXD58p+yJjQpjnR9GrLWU9hek/A6hlQe4ztfRqCQceYrt8w9F1kG56sJyHecPqvuMO5+Qh+mdHpuicdxCMJZpKgmhgfpGro5YKaaxqifeNBw4/uyUP0J4GUkAOuy0744ZHxW7+jNWmwe3lPL8EaZ1GnKWMujos02hZcYxxLHT4NsFPI3/qrEojigD6m46J4IlsJq6O7GYVdC7Lw9soOAmYwclOdOTIcongjTS0mObLpxSE+JsD+LjKtJghYvVw8h8tj328DBcJz8BFn3zDBxMCmsnqsdoOOSjVGB7LF8Li10DIhWZdRt3AUE9Cq2g+Y4juQheUaa3Ki4pYRnEkhli/9+fD0zjJymXyL1BS9TFFRgEvTlSJ82QC874Xps6oh/lLZp66LZs/IZRXm8prUnzsFRC8u4AARoQjON3wPg3dB8AKE8XcFfkU3CxIhMzW79pHyMDNgoKpGo4JYsCQGoErqLKlj4xhG0NNBXR5MJ2s8="
    - secure: "a2kXWu3jbb6e8yCsSqVJQJXDa6lU2Rd593MV5LxkABfUHwunVv3fXI4pAV+jGyBKI4z+kcSHczWq0B/yLeuOOLsMLsFiXKniVNrroBkQKERrGySTKZu5SdaIjE//fLIDfrzBpNS4NyYK8VDaDYsRkgiYVlLZ3/SwPHbpMRHrHBudjHc6E9uADO5HXbxHWYZl8bNVJwLyMUFo9xbOKeqf0ejRoAyF/2rhoVPgxnfEeTAg9QXuYTDWf+tlbbPVzYuKtfoOjlAvgy80sFApR2Gq52GpvYN3CD40QrQX4j7L9ifgVLGyqrJ8J/URRaLcWUOor8TmsnNcSLddgOY1kWDX4DF70W9/881mbhvaIYixGX7YTx+n7zhP0Vpq7ygNmDjnnhz+7GWcD3UXHAt0bn3twEy1kcLajy2hOp3Y/Q57Ee1NnC+r+BKKrqKcGj2GoIh8TC/CuioVqCNFnctGBYylCbDNJl4mxLc1pmIw+/TRhEX06tsIfXLj6iwExVZAhhpBiN+GnICFCc48Pjha+e9Q30UmsTWYTBx5eZ488B/11byxI3CCqSLiAU3HaHv4gQm37y59AXCkMVMY0bvCFt/5C+fmHDLRcNmqhtZS2u1XTNK6/HQvs1pVAISqQuaVmBOa4IyT93qCdtrMWMzYt2AZiDCha3muxjDGRrpzh0EfwFw="
install:
  - pip install -r app/f_test/requirements.txt
script: ./run_tests.sh
deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    branch: master
