traefik:
  image: traefik
  command: --web --docker --docker.domain=f-test.localhost --logLevel=DEBUG
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml

f-test:
  build: .
  ports:
    - "8000"
  labels:
    - "traefik.backend=f-test"
    - "traefik.enable=true"
    - "traefik.frontend.rule=HostRegexp: {.*}"
    - "traefik.frontend.rule=Path: /, /myip/, /myip"
